- name: Install mysql
  package:
    name:
      - mysql-server
      - mysql-client
    state: latest

- name: Install pip modules
  pip:
    name:
      - PyMySQL
    state: present
    executable: pip3

- name: Start mysql service
  systemd:
    name: mysql
    state: started
    enabled: yes

- name: Change the authentication plugin of MySQL root user to mysql_native_password
  shell: |
    mysql -u root -e 'UPDATE mysql.user SET Password=PASSWORD('{{ mysql_pass }}') plugin="mysql_native_password" WHERE user="root" AND host="%"'
  ignore_errors: yes

#- name: Set MySQL root password
#  mysql_user:
#    login_host: localhost
#    login_user: root
#    check_implicit_admin: yes
#    name: root
#    password: "{{ mysql_pass }}"
#    priv: '*.*:ALL,GRANT'
#    state: present

- name: Reload privilege tables
  mysql_query:
    login_host: localhost
    login_user: root
    login_password: "{{ mysql_pass }}"
    query: FLUSH PRIVILEGES

- name: Create todo database
  mysql_db:
    login_host: localhost
    login_user: root
    login_password: "{{ mysql_pass }}"
    name: "{{ mysql_db }}"
    state: present

- name: Update mysql config file to allow remote connections
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: "^bind-address=*"
    line: "bind-address = 0.0.0.0"
    backup: yes