- name: Install mysql
  package:
    name:
      - mysql-server
      - mysql-client
    state: latest

- name: Install pip modules
  pip:
    name:
      - PyMySQL
    state: present
    executable: pip3

- name: update mysql config file to allow remote connections
  command: |
    sed -e 's/^bind-address=*/#&/' /etc/mysql/mysql.conf.d/mysqld.cnf

- name: Start mysql service
  systemd:
    name: mysql
    state: started
    enabled: yes

- name: Change the authentication plugin of MySQL root user to mysql_native_password
  shell: |
    mysql -u {{ mysql_user }} -e 'UPDATE mysql.user SET plugin="mysql_native_password" WHERE user="{{ mysql_user }}" AND host="%"'
  ignore_errors: yes

- name: Set MySQL root password
  mysql_user:
    login_host: "{{ mysql_host }}"
    login_user: "{{ mysql_user }}"
    login_password: ''
    name: "{{ mysql_user }}"
    password: "{{ mysql_pass }}"
    state: present
  ignore_errors: yes

- name: Reload privilege tables
  command: |
    mysql -u {{ mysql_user }} -p{{ mysql_pass }} -ne 'FLUSH PRIVILEGES'
  changed_when: False

- name: Create todo database
  mysql_db:
    login_user: root
    login_password: "{{ mysql_pass }}"
    name: "{{ mysql_db }}"
    state: present