---
- name: sql installation
  hosts: db
  become: yes
  tasks:

    - name: create mysql group
      group:
        name: {{ db_group }}
        state: present

    - name: create mysql user
      user:
        name: {{ db_user }}
        system: yes
        shell: /bin/false
        group: {{ db_group }}
        state: present

    - name: download sql archive
      get_url:
        url: https://downloads.mysql.com/archives/get/p/23/file/mysql-5.7.37-linux-glibc2.12-x86_64.tar.gz
        dest: /home/ubuntu

    - name: unarchive the package
      unarchive:
        src: /home/ubuntu/mysql-5.7.37-linux-glibc2.12-x86_64.tar.gz
        dest: /usr/local/
        remote_src: yes

    - name: create mysql softlik
      file:
        src: /usr/local/mysql-5.7.37-linux-glibc2.12-x86_64
        dest: /usr/local/mysql
        state: link

    - name: create mysql-files folder
      file:
        path: /usr/local/mysql/mysql-files
        state: directory

    - name: update permissions
      file:
        path: /usr/local/mysql
        user: {{ db_user }}
        group: {{ db_group }}
        mode: 775
        recurse: yes
        state: directory

    - name: initialize sql db
      command:
        chdir: /usr/local/mysql
        cmd: "{ item }"
      loop:
        - bin/mysqld --initialize-insecure --user={{ db_user }}
        - bin/mysql_ssl_rsa_setup

    - name: start mysql service
      command:
        chdir: /usr/local/mysql
        cmd: support_files/mysql.server start




