---
- name: Install requirements
  hosts: all
  become: yes
  tasks:
    - include_tasks: requirements.yaml

- name: Setup and configure database
  hosts: database
  become: yes
  tasks:
    - include_tasks: database.yaml

- name: Setup and configure frontend application
  hosts: frontend
  become: yes
  tasks:
    - include_tasks: frontend.yaml
