---
- name: Install requirements
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - include_tasks: requirements.yaml

- name: SQL Database
  import_playbook: database.yaml

- name: Application
  import_playbook: frontend.yaml
