---
- name: create infrastructure
  hosts: localhost
  connection: local
  tasks:
    - name: install pip3
      package:
        - python3-pip

    - name: Install boto3 modules
      pip:
        name:
          - boto3
        state: present
        executable: pip3

    - include_tasks: instances.yaml
  tags: infra

- name: Install requirements
  hosts: all
  become: yes
  tasks:
    - include_tasks: requirements.yaml

- name: Setup and configure database
  hosts: db
  become: yes
  tasks:
    - include_tasks: database.yaml

- name: Setup and configure frontend application
  hosts: frontend
  become: yes
  tasks:
    - include_tasks: frontend.yaml
