---
- name: sql installation
  hosts: db
  become: yes
  tasks:
    - name: Update Package Cache (apt/Ubuntu)
      tags: always
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Ubuntu"

    - name: Update Package Cache (dnf/CentOS)
      tags: always
      dnf:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "CentOS"

    - name: Update Package Cache (yum/Amazon)
      tags: always
      yum:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Amazon"

    - name: Install required packages
      package:
        name:
          - mysql-server
          - mysql-client
          - python3
          - python3-pip
        state: latest

    - name: Install pip modules
      pip:
        name:
          - PyMySQL
        state: present
        executable: pip3

    - name: Ensure mysql service is running
      systemd:
        name: mysql
        state: started
        enabled: yes

- name: initialize dabase
  hosts: db
  become: yes
  tasks:
    - name: Change the authentication plugin of MySQL root user to mysql_native_password
      shell: mysql -u root -e 'UPDATE mysql.user SET plugin="mysql_native_password"
      WHERE user="root" AND host="localhost"'

    - name: Flush Privileges
      shell: mysql -u root -e 'FLUSH PRIVILEGES'

    - name: Set MySQL root password
      mysql_user:
        login_host: 'localhost'
        login_user: 'root'
        login_password: ''
        name: 'root'
        password: '{{ mysql_pass }}'
        state: present

    - name: Reload privilege tables
      command: |
        mysql -p{{ mysql_pass }} -ne "{{ item }}"
      with_items:
        - FLUSH PRIVILEGES
      changed_when: False

    - name: create todo database
      command: |
        mysql -p{{ mysql_pass }} -ne "CREATE DATABASE todo"

